name: flute
environment:
  sdk: '>=2.12.0-157.0.dev <3.0.0'
dependencies:
  characters: 1.1.0-nullsafety.5
  collection: 1.15.0-nullsafety.5
  meta: 1.3.0-nullsafety.6
  typed_data: 1.3.0-nullsafety.5
  vector_math: 2.1.0-nullsafety.5
dev_dependencies:
  args: any
  process: any
