name: Flute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [beta, dev]
    steps:
      - name: Job info
        run: |
          echo "Triggered ${{ github.event_name }}"
          echo "Running on ${{ runner.os }}"
          echo "Branch: ${{ github.ref }}; repo: ${{ github.repository }}."
      - name: Fetch sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
        with:
          sdk: ${{ matrix.sdk }}
      - name: Pub get
        run: |
          (cd engine && dart pub get)
          (cd framework && dart pub get)
          (cd benchmarks && dart pub get)
          (cd script && dart pub get)
      - name: Analyze
        run: |
          dart analyze --fatal-infos --fatal-warnings
      - run: echo "🍏 This job's status is ${{ job.status }}."
